export const LOCAL_NOTE_PROGRAM_ID =
    "YJzQvKvDqwGNJx7RbN28PfSrcWgqnvDZJvcoh5kgBtD";

export const LOCATION_MULTIPLE = 100000;
export const LOCATION_MULTIPLE_APROX = 100;
export const LOCATION_MULTIPLE_APROX_COEFF = LOCATION_MULTIPLE / LOCATION_MULTIPLE_APROX;